"""initial schema

Revision ID: 069cd172c734
Revises: 
Create Date: 2026-09-18 20:53:47.870847

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069cd172c734'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('unit_system', sa.Text(), server_default='metric', nullable=False),
    sa.Column('timezone', sa.Text(), server_default='UTC', nullable=False),
    sa.Column('goal_weight_kg', sa.Float(), nullable=True),
    sa.Column('weekly_run_goal_m', sa.Float(), nullable=True),
    sa.Column('max_hr', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("unit_system IN ('metric', 'imperial')", name='ck_users_unit_system'),
    sa.CheckConstraint('max_hr IS NULL OR (max_hr >= 100 AND max_hr <= 250)', name='ck_users_max_hr'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', name='uq_users_username')
    )
    op.create_table('body_measurements',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('site', sa.Text(), nullable=False),
    sa.Column('value_cm', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('value_cm > 0', name='ck_body_measurements_value_cm'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercises',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_lower', sa.Text(), nullable=False),
    sa.Column('muscle_group', sa.Text(), server_default='other', nullable=False),
    sa.Column('category', sa.Text(), server_default='other', nullable=False),
    sa.Column('equipment', sa.Text(), server_default='other', nullable=False),
    sa.Column('is_compound', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("category IN ('push', 'pull', 'legs', 'other')", name='ck_exercises_category'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name_lower', name='uq_exercises_user_id_name_lower')
    )
    op.create_index('ix_exercises_user_archived', 'exercises', ['user_id', 'is_archived'], unique=False)
    op.create_table('progress_photos',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shoes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('purchased_at', sa.Date(), nullable=True),
    sa.Column('initial_distance_m', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('retired_at', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name', name='uq_tags_user_id_name')
    )
    op.create_table('weight_entries',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('measured_at', sa.DateTime(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('body_fat_pct', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('body_fat_pct IS NULL OR (body_fat_pct > 0 AND body_fat_pct < 100)', name='ck_weight_entries_body_fat_pct'),
    sa.CheckConstraint('weight_kg > 0', name='ck_weight_entries_weight_kg'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_weight_entries_user_id_measured_at', 'weight_entries', ['user_id', 'measured_at'], unique=False)
    op.create_table('workout_templates',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_lower', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name_lower', name='uq_workout_templates_user_id_name_lower')
    )
    op.create_index('ix_workout_templates_user_archived', 'workout_templates', ['user_id', 'is_archived'], unique=False)
    op.create_table('cardio_activities',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Text(), server_default='run', nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('avg_hr', sa.Integer(), nullable=True),
    sa.Column('route_name', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('shoe_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.Text(), server_default='manual', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("type IN ('run', 'cycle', 'swim', 'row', 'other')", name='ck_cardio_activities_type'),
    sa.CheckConstraint('avg_hr IS NULL OR (avg_hr >= 30 AND avg_hr <= 250)', name='ck_cardio_activities_avg_hr'),
    sa.CheckConstraint('distance_m IS NULL OR distance_m >= 0', name='ck_cardio_activities_distance_m'),
    sa.CheckConstraint('duration_s > 0', name='ck_cardio_activities_duration_s'),
    sa.ForeignKeyConstraint(['shoe_id'], ['shoes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cardio_activities_user_id_performed_at', 'cardio_activities', ['user_id', 'performed_at'], unique=False)
    op.create_table('template_exercises',
    sa.Column('template_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('target_sets', sa.Integer(), nullable=True),
    sa.Column('target_reps', sa.Integer(), nullable=True),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_template_exercises_position'),
    sa.CheckConstraint('target_reps IS NULL OR target_reps > 0', name='ck_template_exercises_target_reps'),
    sa.CheckConstraint('target_sets IS NULL OR target_sets > 0', name='ck_template_exercises_target_sets'),
    sa.CheckConstraint('target_weight_kg IS NULL OR target_weight_kg > 0', name='ck_template_exercises_target_weight_kg'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'position', name='uq_template_exercises_template_position')
    )
    op.create_table('workouts',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workouts_user_id_performed_at', 'workouts', ['user_id', 'performed_at'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('workout_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('superset_group', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('position >= 0', name='ck_workout_exercises_position'),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_id', 'position', name='uq_workout_exercises_workout_position')
    )
    op.create_table('workout_tags',
    sa.Column('workout_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('workout_id', 'tag_id')
    )
    op.create_index('ix_workout_tags_tag_id', 'workout_tags', ['tag_id'], unique=False)
    op.create_table('sets',
    sa.Column('workout_exercise_id', sa.Uuid(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('rpe', sa.Float(), nullable=True),
    sa.Column('is_warmup', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_drop_set', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('reps >= 1', name='ck_sets_reps'),
    sa.CheckConstraint('rpe IS NULL OR (rpe >= 0 AND rpe <= 10)', name='ck_sets_rpe'),
    sa.CheckConstraint('set_number >= 1', name='ck_sets_set_number'),
    sa.CheckConstraint('weight_kg > 0 OR weight_kg IS NULL', name='ck_sets_weight_kg'),
    sa.ForeignKeyConstraint(['workout_exercise_id'], ['workout_exercises.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_exercise_id', 'set_number', name='uq_sets_workout_exercise_set_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sets')
    op.drop_index('ix_workout_tags_tag_id', table_name='workout_tags')
    op.drop_table('workout_tags')
    op.drop_table('workout_exercises')
    op.drop_index('ix_workouts_user_id_performed_at', table_name='workouts')
    op.drop_table('workouts')
    op.drop_table('template_exercises')
    op.drop_index('ix_cardio_activities_user_id_performed_at', table_name='cardio_activities')
    op.drop_table('cardio_activities')
    op.drop_index('ix_workout_templates_user_archived', table_name='workout_templates')
    op.drop_table('workout_templates')
    op.drop_index('ix_weight_entries_user_id_measured_at', table_name='weight_entries')
    op.drop_table('weight_entries')
    op.drop_table('tags')
    op.drop_table('shoes')
    op.drop_table('progress_photos')
    op.drop_index('ix_exercises_user_archived', table_name='exercises')
    op.drop_table('exercises')
    op.drop_table('body_measurements')
    op.drop_table('users')
    # ### end Alembic commands ###
