"""phase2 schema

Revision ID: 223a04bfe427
Revises: 069cd172c734
Create Date: 2026-09-19 00:59:30.209579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223a04bfe427'
down_revision: Union[str, Sequence[str], None] = '069cd172c734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_plans',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_lower', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name_lower', name='uq_weekly_plans_user_id_name_lower')
    )
    op.create_index('uq_weekly_plans_active_per_user', 'weekly_plans', ['user_id'], unique=True, sqlite_where=sa.text('is_active = 1'))
    op.create_table('weekly_plan_slots',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('day_of_week >= 0 AND day_of_week <= 6', name='ck_weekly_plan_slots_day_of_week'),
    sa.ForeignKeyConstraint(['plan_id'], ['weekly_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['workout_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_id', 'day_of_week', name='uq_weekly_plan_slots_plan_day')
    )
    op.create_table('cardio_splits',
    sa.Column('cardio_activity_id', sa.Uuid(), nullable=False),
    sa.Column('split_number', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('distance_m > 0', name='ck_cardio_splits_distance_m'),
    sa.CheckConstraint('duration_s > 0', name='ck_cardio_splits_duration_s'),
    sa.CheckConstraint('split_number >= 1', name='ck_cardio_splits_split_number'),
    sa.ForeignKeyConstraint(['cardio_activity_id'], ['cardio_activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cardio_activity_id', 'split_number', name='uq_cardio_splits_activity_number')
    )
    op.add_column('exercises', sa.Column('goal_weight_kg', sa.Float(), sa.CheckConstraint('goal_weight_kg IS NULL OR goal_weight_kg > 0', name='ck_exercises_goal_weight_kg'), nullable=True))
    op.add_column('exercises', sa.Column('goal_reps', sa.Integer(), sa.CheckConstraint('goal_reps IS NULL OR goal_reps > 0', name='ck_exercises_goal_reps'), nullable=True))
    op.add_column('exercises', sa.Column('goal_target_date', sa.Date(), nullable=True))
    op.add_column('exercises', sa.Column('goal_reps_bodyweight', sa.Integer(), sa.CheckConstraint('goal_reps_bodyweight IS NULL OR goal_reps_bodyweight > 0', name='ck_exercises_goal_reps_bodyweight'), nullable=True))
    op.add_column('users', sa.Column('goal_rate_kg_per_week', sa.Float(), sa.CheckConstraint('goal_rate_kg_per_week IS NULL OR goal_rate_kg_per_week != 0', name='ck_users_goal_rate_kg_per_week'), nullable=True))
    op.add_column('users', sa.Column('goal_monthly_mode', sa.Text(), sa.CheckConstraint("goal_monthly_mode IS NULL OR goal_monthly_mode IN ('target', 'rate')", name='ck_users_goal_monthly_mode'), nullable=True))
    op.add_column('users', sa.Column('goal_monthly_target_kg', sa.Float(), sa.CheckConstraint('goal_monthly_target_kg IS NULL OR goal_monthly_target_kg > 0', name='ck_users_goal_monthly_target_kg'), nullable=True))
    op.add_column('users', sa.Column('goal_monthly_rate_kg', sa.Float(), sa.CheckConstraint('goal_monthly_rate_kg IS NULL OR goal_monthly_rate_kg != 0', name='ck_users_goal_monthly_rate_kg'), nullable=True))
    op.add_column('users', sa.Column('height_cm', sa.Float(), sa.CheckConstraint('height_cm IS NULL OR height_cm > 0', name='ck_users_height_cm'), nullable=True))
    op.add_column('users', sa.Column('goal_weight_target_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('goal_weight_target_kg', sa.Float(), sa.CheckConstraint('goal_weight_target_kg IS NULL OR goal_weight_target_kg > 0', name='ck_users_goal_weight_target_kg'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'goal_weight_target_kg')
    op.drop_column('users', 'goal_weight_target_date')
    op.drop_column('users', 'height_cm')
    op.drop_column('users', 'goal_monthly_rate_kg')
    op.drop_column('users', 'goal_monthly_target_kg')
    op.drop_column('users', 'goal_monthly_mode')
    op.drop_column('users', 'goal_rate_kg_per_week')
    op.drop_column('exercises', 'goal_reps_bodyweight')
    op.drop_column('exercises', 'goal_target_date')
    op.drop_column('exercises', 'goal_reps')
    op.drop_column('exercises', 'goal_weight_kg')
    op.drop_table('cardio_splits')
    op.drop_table('weekly_plan_slots')
    op.drop_index('uq_weekly_plans_active_per_user', table_name='weekly_plans', sqlite_where=sa.text('is_active = 1'))
    op.drop_table('weekly_plans')
    # ### end Alembic commands ###
